name: Publish Package

on:
  push:
    branches:
      - main

jobs:

  publish:
    uses: ElMoha943/github-workflows/.github/workflows/release-package.yml@master
    with:
      package_file: Packages/com.valenvrc.whitelistedtp/package.json

  update-listing:
    needs: publish

    uses: ElMoha943/github-workflows/.github/workflows/update-package-listing.yml@master

    secrets:
      LISTING_TOKEN: ${{ secrets.LISTING_TOKEN }}